### PR TITLE
render page controls in storyboard

### PR DESCRIPTION
**Pull request by finngaida**

### CODE REVIEW

**Comment by popwarsweet** [comment]
@finngaida Thanks so much for submitting this! I noticed some constraints have been modified in each control. Instead of fiddling with any constraints in the storyboard, can you simply change the `Intrinsic Size` from `Placeholder` to `Default (System Size)`? This will respect the current vertical layout of the controls as well as the intrinsic content size of each control.

**Comment by finngaida** [comment]
Just committed, this should work better, you're right

**Comment by popwarsweet** [comment]
@finngaida looks like quite a few extra files were bundled into this commit (project files/pod junk). It should just be the 4 source files and storyboard. Thanks.

**Comment by finngaida** [comment]
Ah god damnit my gitflow could really use some work, one minute...

**Comment by finngaida** [comment]
Okay this should be it

**Comment by popwarsweet** [comment]
thanks again!

**Comment by finngaida** [comment]
thanks for the inspiration!

**Pull request merged**
